### PR TITLE
package components, polished vignette

### PR DESCRIPTION
**Pull request by schifferl**
I worked really hard to polish the format of the vignette but didn't change the content. I would recommend merging and then you can build the vignette to see the changes. There were a few other files added that will help users working with the package in RStudio. The build and check commands now work for the package.

### CODE REVIEW

**Comment by schifferl** [comment]
The merging suggest conflicts... these are just because I moved things around a lot, you shouldn't have issues.

**Comment by schifferl** [comment]
I guess it actually happened because Marcel made some changes that I didn't pull in before submitting.

**Comment by schifferl** [comment]
Sorry for the endless comments, I fixed everything and you should be able to merge without issue now.

**Comment by LiNk-NY** [comment]
There's still an issue with reverting the formatting. If you can somehow save just your corrections without reverting the formatting that would be good.

**Comment by lgeistlinger** [comment]
Thanks Lucas, I merged manually.

**Pull request closed without merging**
